### ISSUE TITLE
Outline / Table of Contents

### ISSUE THREAD

**Issue by rowanc1** [iooxa/ink-article#2]
Outline:

![ink-outline](https://user-images.githubusercontent.com/913249/79379402-1f599d80-7f1c-11ea-9881-b894e7228eb1.gif)

I also like (https://firebase.google.com/docs/firestore/manage-data/transactions):
![image](https://user-images.githubusercontent.com/913249/79379455-300a1380-7f1c-11ea-8562-c421b49144a8.png)

As well as some of the recent Jupyter-book work with sphinx.

There is some question I think about the difference between an outline and TOC, and what was previously created is more of a TOC - I think there needs to be both created to add a few levels of structure.

Found this snippet: http://www.professays.com/thesis/thesis-table/
> **What is the difference between a table of contents and an outline?**
> A table of contents indicates the structure of the paper, specifying its chapters, sub-chapters and the pages where they can be found. An outline, on the other hand, represents another form of summary, organized upon the main ideas of the paper, which describe a hierarchical or logical structuring of the information. It is recommended to write the outline before the actual paper, so that you follow the main ideas accordingly. While the table of contents points to the page numbers of chapters and sub-chapters, as they can be found in the paper, the outline does not provide such information.

cc @choldgraf

**Comment by rowanc1** [comment]
Some progress:

I have added links and shows which outline elements are currently on the page (or the last one seen).

![ink-outline](https://user-images.githubusercontent.com/913249/79399572-f5ff3880-7f40-11ea-9cc6-42c4f5d90aab.gif)

I think it is actually a nice compromise between all of the ones that I have seen.

@choldgraf curious about your style insights here! :)

**Comment by rowanc1** [comment]
closed in #8

**Comment by choldgraf** [comment]
that was fast :-)

We ran into the same naming challenge in jupyter book - to be honest I'm not sure the best naming convention because websites allow for much more flexibility about a document's structure than PDFs etc. I like the hover-TOC to the right, though I wonder if it's worth adding some other visual cue so that users know what it is. For the power-user-type, they may be familiar with Dropbox-style lines, but I wonder if the same is true for a more casual user

**Comment by rowanc1** [comment]
Ha, yeah, powering through some stuff. And closing issues feels like progress. Thanks for chiming in. :)

I am sort of thinking that the structure follows `<ink-outline>` and `<ink-nav>`, with the `nav` one being more like the side-bar navigation. The outline has a `for` attribute, which you can specify what the outline is "for" (!!)  by the ID of the article, etc. So I think it is flexible.

I have also added an `open` attribute, which can be toggled to keep it open. I have done this to bring it into the article when the page is small. I really like the small footprint, but the component is flexible from the developer's standpoint to do both!

![image](https://user-images.githubusercontent.com/913249/79594541-69688d80-809a-11ea-84f3-056abfaefef6.png)

Good point about the onboarding: I might also throw an initial animation in there to bring attention to it? That might help people learn?

**Comment by choldgraf** [comment]
I like animations for that kinda thing, yeah - it's also the reason that I decided to explicitly put the words "table of contents" in the sphinx-book-theme UI so it was painfully obvious haha.

For the sidebar etc, I think the nomenclature we are going with in jupyter book is:

* Between-page sidebar to the left == "Navigation bar" or "Navbar"
* Within-page nav to the right == "Table of Contents" or "Tocbar"

**Comment by rowanc1** [comment]
Yep, totally agree. I just didn't want to write out `<ink-table-of-contents>` and didn't really like the look of `<ink-toc>` (which is what a few other similar packages have gone with, it makes me want a matching `tic`, probably a hangup from my [Matlab days](https://www.mathworks.com/help/matlab/ref/tic.html)).

I kinda liked the google doc terminology here. They can "insert" a table of contents, or you can "show" the document outline.

Both are basically the same thing, TOC though to me means page numbers, etc. :)

I will tag you again when I am making some of the nav stuff. I want this to stay similar enough to Jupyter book!
